version: "3.8"

services:
  nodered:
    build: .
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    environment:
      - NODE_RED_ENABLE_PROJECTS=true

volumes:
  nodered_data:
